# _**Tiana Turner Section 5 Homework**_

### **1. What does Pandas stand for?**
#### Panel data or Python data analysis

### **2. What are the 2 collections used in Pandas?**
#### Series and Dataframes

### **3. Name 4 things Pandas can do for us.**
#### load, manipulate, analyze, model

### **4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?**
#### inplace = True

### **5. What is a CSV?**
#### It is a comma seperated file that contains plain text with a format that can be read by everyone including pandas.

### **6. When cleaning data what values do we not like in our data?**
#### Null values, duplicate values, incorrect values


In [52]:
#7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- `.reshape()`

import numpy as np

a_1 = np.arange(12).reshape((2, 3, 2))
a_1

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [108]:
#8. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20

lin = np.linspace(0, 20, num=6)
lin

array([ 0.,  4.,  8., 12., 16., 20.])

In [41]:
#9. Make a Deep Copy of the above array

import copy

lin = np.linspace(0, 20, num=6)
lin2 = copy.deepcopy(lin)

lin2


array([ 0.,  4.,  8., 12., 16., 20.])

In [107]:
#10. Concatenate these 3 arrays into a new array named 'newArray'...

a_x=np.array([[25, 16]])
a_y=np.array([[11, 2], [13, 4]])
a_z=np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((a_z, a_x, a_y), axis=0)
print(newArray)

#11. Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)
print (sortedArray)


[[ 7 81]
 [ 5  6]
 [11 12]
 [25 16]
 [11  2]
 [13  4]]
[[ 7 81]
 [ 5  6]
 [11 12]
 [16 25]
 [ 2 11]
 [ 4 13]]


In [106]:
#12. Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.
reshape_a1 = a_1.reshape(4,3)

a, b, c, d = reshape_a1

print(a)
print(b)
print(c)
print(d)



[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [105]:
#13. Combine and sort the following arrays into one called 'comboArray' ...

one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate([three, one, two])

print(comboArray)

#14. Take 'comboArray' and perform the following slicing activities:

#- print sec1 - the 2nd element
print(comboArray[1:2])
    
#- print sec2 - all elements from the 3rd element to the last
print(comboArray[2:])
    
#- print sec3 - all elements from the 4th to the 14th elements
print(comboArray[3:14])
    
#- print sec4 - the last 6 elements
print(comboArray[18:])
    
#- print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
print(comboArray[-24:-8])
    
#- print sec6 - from #20 every even element to the end
print(comboArray[::2])
    
#- print sec7 - from the last element moving backward, every 5th element.
print(comboArray[-1::-5])
    

[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[1]
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14 15]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17]
[ 0  2  4  6 10 12 14 16 20 22 24 26]
[27 22 15 10  3]


In [111]:
#15. Using `Series`, create a `DataFrame` that looks like this:
import pandas as pd

Ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name='Ingredients')
Quantity = pd.Series([4, 1, 2, 1], name= 'Quantity')
Unit = pd.Series(["cups", "cup", "large", "can"], name='Unit')

Dinner=pd.concat([Ingredients, Quantity, Unit], axis=1)

Dinner

Ingredients  Quantity   Unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can

In [121]:
#16. Take this data and create a DataFrame named studentData

Data ={'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'], 
              'Height': [5.1, 6.2, 5.1, 5.2], 
              'Qualification': ['Msc', 'MA', 'Msc', 'Msc'], 
              'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'], 
              'Age': [21, 23, 24, 21], 
              'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'], 
              'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']}

studentData =pd.DataFrame(Data)

#17. Add a new column to the DataFrame with the following deserts:
deserts= ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

studentData['desert']= deserts

#18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_values(by = ['address', 'Name'], inplace=True)

studentData

Name  Height Qualification  address  Age        Pets           sport  \
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding   
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket   
0      Jai     5.1           Msc    Delhi   21         Dog           Darts   
1  janusha     6.2            MA     Doha   23       Bunny      Basketball   

         desert  
2       waffels  
3  Carrot Halwa  
0     ice cream  
1  Cashew Fudge

In [133]:
#19. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df.to_csv('cows_and_goats.csv')



In [132]:
#20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. 

vegetables = pd.DataFrame([['green', 'broccoli'], ['red', 'bell pepper']], columns= ['color', 'name'])

vegetables.to_csv('Vegetable_colors.csv')

# (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

vege_C = pd.read_csv('Vegetable_colors.csv')

vege_C = vegetables.replace(to_replace='broccoli', value='asparagus')

vege_C.to_csv('Vegetable_Change.csv')